sudo: true
dist: trusty
before_install:
     - chmod +x ./travis-script/main.sh
     - chmod +x ./travis-script/test-dockerfile.sh
     - chmod +x ./travis-script/test-build-push.sh
jobs:
  include:
    - stage: check Dockerfile
      script: ./travis-script/main.sh

    

